### ISSUE TITLE
Jade runtime include does not work with npm 3

### ISSUE THREAD

**Issue by WolfgangFellger** [brunch/jade-brunch#24]
[Concatenating the path for `.include`](https://github.com/brunch/jade-brunch/blob/dea088/index.js#L61) doesn't work anymore with npm 3. This release aggressively flattens the tree, so jade will most likely (but not certainly) be located at `__dirname/../jade`. You should use `require.resolve('jade')` instead.

**Comment by AdrianSchurz** [comment]
+1

**Comment by vizv** [comment]
+1

**Comment by gcatto** [comment]
Any update on when this might be fixed?

**Comment by es128** [comment]
Fixed in 1.8.2
