### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by alancwoo** [brunch/jade-brunch#30]
Through my brunch config, I am combining vendor js files into a separate file:

```
module.exports = config:
  files:
    javascripts: joinTo:
      'vendor.js': /^(?!app\/)/
      'app.js': /^app\//
```

This was working before, for some reason now I am getting `Uncaught ReferenceError: require is not defined`, which occurs because the `node_modules/jade/runtime.js` calls `require.register('browser-resolve/empty', function(exports,req,module){`

I'm not sure how to resolve this? Previously, when using earlier versions of `jade-brunch` and `jade-static-brunch`, the npm module for jade wasn't installed into my `node_modules` directory.

---

My dependencies in `package.json`:

```
"devDependencies": {
    "brunch": "^2.4.2",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "postcss-brunch": "^0.5.0",
    "stylus": "^0.53.0",
    "stylus-brunch": "^2.0.0",
    "auto-reload-brunch": "^1.8.1",
    "jade-brunch": "^2.0.0",
    "static-jade-brunch": "^1.8.0"
  }
```

Previously working (with older versions):

```
  "devDependencies": {
    "autoprefixer": "^6.0.3",
    "brunch": "^1.8.5",
    "css-brunch": "^1.7.0",
    "jade-brunch": "^1.8.1",
    "javascript-brunch": "^1.8.0",
    "postcss-brunch": "^0.5.0",
    "sass-brunch": "^1.9.1",
    "static-jade-brunch": "^1.8.0"
  }
```

**Comment by dwoodsDev** [comment]
+1 Having the same issue.

**Comment by denysdovhan** [comment]
@alancwoo hi!

If this issue is still relevant, please, try to update your Brunch and dependencies to the latest versions. If this won't help, I will be glad if you wrap up all of this files in repo, thus it would help me to solve your problem.
