### ISSUE TITLE
Jade is in the process of being renamed to pug

### ISSUE THREAD

**Issue by mcfarljw** [brunch/jade-brunch#31]
https://github.com/pugjs/pug/issues/2184

Not super urgent right now, but it looks like within the next 6 months `jade` will be phased out on npm in favor of `pug` due to some trademark issue.

**Comment by paulmillr** [comment]
"pug" is in 2.0-α now. we probably don't want to use α ver. I think that was a shitty decision to rename it while not having a stable version to use.

**Comment by bendoh** [comment]
Bumping this: the rename to pug is complete.

**Comment by shvaikalesh** [comment]
> 2.0.0-beta11 is the latest of 21 releases

When it is expected to release?

**Comment by ooloth** [comment]
Any chance of renaming to pug and working with .pug files?

**Comment by paulmillr** [comment]
See my previous comment.
