### ISSUE TITLE
Add options to not compile include/extend partials during static compilation.

### ISSUE THREAD

**Issue by DoumanAsh** [brunch/jade-brunch#35]
As of now brunch copies everything from assets directory so every template will be copied.
It would be great to have option to not copy files that are only included. Maybe similarly to the way brunch ignores files for compilation( by default files starting with _) are ignored.

On other hand maybe it would be better to have some means of pre-compilation outside of static compilation?(i.e. when templates ain't in assets folder)

**Comment by shvaikalesh** [comment]
Hello there, @DoumanAsh.

Not copying dependent files is an awesome idea, but it is a bit tricky in implementation. For now, you can tweak `conventions.assets` to not include partials like:

```js
        assets:
        [
            "app/pages/",
            "app/pages/*.html",
            "app/static/**",
        ],
```

**Comment by DoumanAsh** [comment]
Hm... i'm not exactly sure i got your idea of not including partials.
At first i tried to just move them into a separate directory inside templates and use glob pattern to include only actual templates, but it kinda broken for some reason.

```
assets: [
    ^app\/assets/,
    "app/templates/*.jade"
],
```

I just get strange error:
```
error: Path must be a string. Received undefined
```
Maybe brunch problem or i'm not exactly right in this glob pattern

**Comment by shvaikalesh** [comment]
Does the error persist in Brunch from `master`?

**Comment by DoumanAsh** [comment]
The error is different:
```
30 Dec 11:44:15 - error: Processing of app/templates/_head.jade failed.

   Asset file app/templates/_head.html was moved from assets directory
```

**Comment by shvaikalesh** [comment]
Yep, that is kinda intended. Please, add `"app/templates/"` before `""app/templates/*.jade"` and try again.

**Comment by DoumanAsh** [comment]
With that it works. I'm not exactly sure how these patterns are used, but now it is ok with something like that:
```
/^app\/assets/,
'app/templates/',
'app/templates/[a-zA-Z0-9]*.jade',
```

With that i kinda emulate skipping files that are starting with `_`

**Comment by shvaikalesh** [comment]
I believe `'app/templates/!(_).jade'` should work to.

Let's leave this open until I figure out a better to do this. I care about static sites + Brunch, more improvements are coming.

**Comment by DoumanAsh** [comment]
Btw, i forgot to mention, there is still issue of useless code being included for not statically compiled templates.

Each non-asset template is still being compiled into js code :(

**Comment by shvaikalesh** [comment]
Will look into that, thanks for the report.
