### ISSUE TITLE
Cannot re-compile after fixing static jade template syntax error

### ISSUE THREAD

**Issue by DoumanAsh** [brunch/jade-brunch#37]
## Way to reproduce
1) Use static templates.
2) `brunch watch --server`
3) Introduce any syntax error in template. //Error is issued by brunch
4) Fix error. -> The **same error** is issued by brunch(exactly the same output).

## Workaround:
Terminate brunch and start again. Everything works fine.

##
It is unclear how it is possible, but for some reason after fixing error, exactly the same error appears in console(even though template is no longer the same)

**Comment by shvaikalesh** [comment]
Hi @DoumanAsh, and happy holidays.

I am already working on it, and plan to land the fix this weekend. Sadly, this is not regression. Brunch `~2.8` experience the same issues.
